### ISSUE TITLE
Lab Suggestions

### ISSUE THREAD

**Issue by terrymandin** [Azure-Samples/avm-terraform-labs#1]
Great lab.  I just ran through it.  Some suggestions for the lab are below:

1. In the prerequisites, add a version number for Terraform.  e.g. 1.7
1. In Part 1, step 2, add ```cd avm-lab```
1. In Part 1, step 12, let the users know what success looks like.  eg:
![image](https://github.com/Azure-Samples/avm-terraform-labs/assets/833055/733bde19-8957-4dff-9598-3f09e483a4a0)
Also point them to the Outputs for the resource group name:
![image](https://github.com/Azure-Samples/avm-terraform-labs/assets/833055/28820edd-ab52-4375-ad1d-30fd657965f8)
1. In Part 2, step 5, suggest pointing users to the [VNet AVM Terraform registry](https://registry.terraform.io/modules/Azure/avm-res-network-virtualnetwork/azurerm/latest) and [VNet AVM opensource](https://github.com/Azure/terraform-azurerm-avm-res-network-virtualnetwork) for the module for review.
1. Note that the copy commands are all for Linux (e.g. forward slash "/").  Some users may be using Windows.
1. In Part 5, there is no mention of calling Terraform apply

**Comment by jaredfholgate** [comment]
I've added these updates, thanks.
