### ISSUE TITLE
Error in part 4 - storage account during deployment - Error: Cycle: module.key.vault...

### ISSUE THREAD

**Issue by mgibson85** [Azure-Samples/avm-terraform-labs#17]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> During https://github.com/Azure-Samples/avm-terraform-labs?tab=readme-ov-file#part-4---storage-account
cd avm-lab
copy ../avm-terraform-labs/labs/part04-storage-account/* .
terraform init -upgrade
terraform apply -auto-approve

### Any log messages given by the failure
>PS F:\avm-lab> terraform apply -auto-approve
│ Error: Cycle: module.key_vault.output.keys_resource_ids (expand), module.key_vault.module.keys.output.versionless_id (expand), module.key_vault.module.keys.local.role_definition_resource_substring (expand), module.key_vault.module.keys.var.role_assignments (expand), module.key_vault.module.keys.azurerm_role_assignment.this, module.key_vault.module.keys.output.resource_versionless_id (expand), module.key_vault.module.keys.output.id (expand), module.key_vault.module.keys.var.rotation_policy (expand), module.key_vault.module.keys.var.tags (expand), module.key_vault.module.keys.var.opts (expand), module.key_vault.module.keys.var.type (expand), module.key_vault.module.keys.var.key_vault_resource_id (expand), module.key_vault.module.keys.var.curve (expand), module.key_vault.module.keys.var.not_before_date (expand), module.key_vault.module.keys.var.expiration_date (expand), module.key_vault.module.keys.azurerm_key_vault_key.this, module.key_vault.module.keys.output.resource_id (expand), module.key_vault.module.keys.var.size (expand), module.key_vault.module.keys (close), module.key_vault (close), module.key_vault.var.keys (expand), module.key_vault.time_sleep.wait_for_rbac_before_key_operations, module.key_vault.module.keys (expand), module.key_vault.module.keys.var.name (expand)

### Expected/desired behavior
>

### OS and Version?
> Windows 11

### Versions
> az version     
{
  "azure-cli": "2.61.0",
  "azure-cli-core": "2.61.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "account": "0.2.5",
    "azure-devops": "0.26.0"
  }
}

> terraform version
Terraform v1.8.5
on windows_amd64
>+ provider registry.terraform.io/azure/azapi v1.13.1
>+ provider registry.terraform.io/hashicorp/azurerm v3.107.0
>+ provider registry.terraform.io/hashicorp/http v3.4.3
>+ provider registry.terraform.io/hashicorp/random v3.6.2
>+ provider registry.terraform.io/hashicorp/time v0.11.2

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jaredfholgate** [comment]
Apologies for the delay, this is now resolved.
