### ISSUE TITLE
Part 3 (Key vault) is referencing an old tag (dns_zone_tags) that is deprecated / removed from the key vault module

### ISSUE THREAD

**Issue by glavman** [Azure-Samples/avm-terraform-labs#19]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow documentation steps, will get stuck when running the terraform plan -out tfplan for step 3 (keyvault)

### Any log messages given by the failure
> │ Error: Unsupported argument
│
│   on avm.private_dns.tf line 14, in module "private_dns_zone_key_vault":
│   14:   dns_zone_tags = var.tags
│
│ An argument named "dns_zone_tags" is not expected here.

### Expected/desired behavior
> Update documentation to correctly reference the updated key vault terraform AVM

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> Win 11

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by glavman** [comment]
Found the pull request/Issue # that references this change in the AVM; 
https://github.com/Azure/terraform-azurerm-avm-res-network-privatednszone/pull/46

**Comment by jaredfholgate** [comment]
Apologies for the delay, this is now resolved
