### ISSUE TITLE
Fix max size for kv name

### ISSUE THREAD

**Issue by khushal08** [Azure-Samples/avm-terraform-labs#2]
Error: Invalid value for variable
│ 
│   on avm.key_vault.tf line 4, in module "key_vault":
│    4:   name                          = local.key_vault_name
│     ├────────────────
│     │ var.name is "kv-demo-wondrous-pipefish"
│ 
│ The name must be between 3 and 24 characters long and can only contain lowercase letters, numbers and dashes.
│ 
│ This was checked by the validation rule at .terraform/modules/key_vault/variables.tf:20,3-13.

**Comment by khushal08** [comment]
@jaredfholgate https://github.com/Azure-Samples/avm-terraform-labs/pull/3

**Comment by jaredfholgate** [comment]
Merged, thanks
