### ISSUE TITLE
Error: retrieving static website properties for Storage Account

### ISSUE THREAD

**Issue by DanGiffen** [Azure-Samples/avm-terraform-labs#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Hi guys,

Great lab but ran into an issue deploying the vm\part 5 with "Error: retrieving static website properties for Storage Account.. Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded"

I tried  to apply again but had the same problem.

### Any log messages given by the failure
![image](https://github.com/Azure-Samples/avm-terraform-labs/assets/38534725/125ab59c-83ac-41fa-b635-bb95c6409804)
### Expected/desired behavior

deploys the relevant resources

### OS and Version?
Windows 11

### Versions
![image](https://github.com/Azure-Samples/avm-terraform-labs/assets/38534725/592260c7-fe9d-45d0-9703-5414142e6025)

### Mention any other details that might be useful
spotted a comment typo in locals
![image](https://github.com/Azure-Samples/avm-terraform-labs/assets/38534725/3d3e01da-0a5f-4e9d-9b1a-27a9c5b0ff7c)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jaredfholgate** [comment]
Hi @DanGiffen. Apologies for the delay in seeing this issue. I have been unable to replicate it so far. I'm wondering if it was a intermittent issue or related to your network setup? Given it is 2 weeks old, I will close for now, but please let me know if you still see it on your side.
