### ISSUE TITLE
Part 3 deployment failed: wrong attribute name

### ISSUE THREAD

**Issue by alenat10** [Azure-Samples/avm-terraform-labs#9]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
follow Lab manual for Part 3 (key vault).

### Any log messages given by the failure
>terraform apply -auto-approve
╷
│ Error: Unsupported attribute
│
│   on non.avm.private_dns.tf line 11, in resource "azurerm_private_dns_zone_virtual_network_link" "key_vault":
│   11:   virtual_network_id    = module.virtual_network.vnet-resource.id
│     ├────────────────
│     │ module.virtual_network is a object
│
│ This object does not have an attribute named "vnet-resource".

### Expected/desired behavior
> keyvault, privatelink and privatelink DNS are installed successfully.

### OS and Version?
> Windows 11 23H2

### Versions
>
23H2
### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by alenat10** [comment]
the issue is related to a syntax error. A pull request is sent.

**Comment by jaredfholgate** [comment]
Closed with https://github.com/Azure-Samples/avm-terraform-labs/pull/15
